### ISSUE TITLE
Auto generate alert rules for any metric absence

### ISSUE THREAD

**Issue by sed-i** [canonical/cos-tool#3]
### Enhancement Proposal

Given a collection of alert rules, we may want to know that the metrics used for calculating the alerts are in fact still served.

Iiuc, if any metric of an `expr` is missing, the alert wouldn't fire.
This may happen when the workload is updated with a breaking change which removes/renames metrics.

In such cases it could be handy to get an alert. `cos-tool` could be used to scan a `prometheus_alert_rules` folder and generate a `.rules` yaml based on the metrics mentioned in the alerts.

**Comment by rbarry82** [comment]
This is not knowable without actually querying Prometheus at runtime, like the [old Grafana charm used to do](https://git.launchpad.net/charm-grafana/tree/src/reactive/grafana.py#n1021).

Even if we wanted to do this, it's not knowable which of these would be present regardless. Picking one from Mimir [somewhat arbitrarily](https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/alerts.yaml#L336), we have absolutely no assurances that this metric will ever exist. At all. We are not using the upstream operator to deploy, so this metric may not be created. Picking from Mimir again, the way Metrics are created in Golang (and other client libraries are similar) is [via `promauto`](https://github.com/grafana/mimir/search?p=1&q=promauto), which maps back through to some `promhttp.Handler()` at a higher level which actually serves the metrics.

But because any given metric doesn't exist at all/is not registered, potentially, until that code path is exercised, means that "until a user/admin accesses some HTTP route, some endpoint, sets some config option, some timer runs" that metric is absent, and may be absent forever if the application is configured differently, this is not reliable.

Even if it were, `cos-tool` generating rules for absences would result in rules which are not reflected in the Juju model at all. An admin looking at `juju show-application|unit` would not be able to infer where the autogenerated rule came from. Additionally, because it would not be in relation data when [`alerts()` is invoked](https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L1169) it would not make it into the workload container anyway without an additional side channel.

**Comment by sed-i** [comment]
> This is not knowable without actually querying Prometheus at runtime

Depends what you mean by "knowable". I meant to use [`absent`](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) or `absent_over_time`.

```
expr: absent(name1) or absent(name2) or ...
for: 30m
```
We wouldn't need to query ourselves.

> we have absolutely no assurances that this metric will ever exist

I'm not sure it's a valid use case with our built-in alerts: we don't just dump anything we find and hope something would be picked up.

> metric doesn't exist at all/is not registered, potentially, until that code path is exercised

Good point.  Arguably, metrics like HTTP codes are labeled, so if we do `absent` without any labels we should be good to go. But this won't necessarily be always the case.

From an on-call point of view, would it be valuable to know about absences for the price of several low-priority `absent` alerts (that would be grouped by the metric name and perhps with an inhibit rule)?

**Comment by rbarry82** [comment]
> Depends what you mean by "knowable". I meant to use [`absent`](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) or `absent_over_time`.
> 
> ```
> expr: absent(name1) or absent(name2) or ...
> for: 30m
> ```

That metric may be in a permanent state of absence if the code path is not executed. This is not a good or reliable strategy.

> We wouldn't need to query ourselves.

We do if we want to know "does this metric exist at all, or has it ever?" Without actually querying Prometheus, it's Schroedinger's metric.
 
> > we have absolutely no assurances that this metric will ever exist
> 
> I'm not sure it's a valid use case with our built-in alerts: we don't just dump anything we find and hope something would be picked up.

We also don't know what users will do. At all. And our build in alerts have [exactly the same Mimir alert](https://github.com/canonical/mimir-k8s-operator/blob/main/src/prometheus_alert_rules/alert-rules.yaml#L336) based on a metric which may never exist. 

It is _far_ better to be conservative then to optimistically generate potentially meaningless alert rules which teach ops/admins that it's ok to ignore the ones which do come in.
 
> > metric doesn't exist at all/is not registered, potentially, until that code path is exercised
> 
> Good point. Arguably, metrics like HTTP codes are labeled, so if we do `absent` without any labels we should be good to go. But this won't necessarily be always the case.

No, we are not good to go. Arguably, metrics like HTTP codes should be labeled, but they are not required to be, the label is relatively freetext, and we do not have anywhere near the level of insight or control into user stories to make any statements about what is or is not good, particularly with a readily-available example of a rule which is more or less _guaranteed_ to send an alert in one of our own charms.
 
> From an on-call point of view, would it be valuable to know about absences for the price of several low-priority `absent` alerts (that would be grouped by the metric name and perhps with an inhibit rule)?

No, it would not be. It would teach admins/operators that the alert system is overly aggressive, and that many/most of the alerts are completely meaningless and can/should be ignored. From an on-call/eval point of view, it would be a negative value proposition to "know about" absences, run a query to check on them, discover that they were _always_ absent, that they were not provided by the charm and that the COS stack had created red herrings on its own, etc.

The idea of creating some kind of mechanism for doing this in a very, _very_ targeted way for a whitelist of rules may be ok, if we can figure out a mechanism for keeping its "responsibility" in relation data in the right place.
